### ISSUE TITLE
Error message prevents app being installed

### ISSUE THREAD

**Issue by R7914T** [amiller27/OverviewAllWindows#11] opened 2017-04-05 18:33 UTC
This message arises when  I try to install the app  on Ubuntu Gnome 16.04.
GLib.FileError: Failed to open file '/home/robins/.local/share/gnome-shell/extensions/OverviewAllWindows@amiller27/schemas/gschemas.compiled': open() failed: No such file or directory

The attached screen shot of the OverviewAllWindows... gnomeshell extension directory shows no schemas directory has been created. 

What is the solution, please?
![selection_015](https://cloud.githubusercontent.com/assets/15330060/24720952/b161f608-1a36-11e7-8b84-745d13dcc672.jpg)

**Comment by bittner** [comment] 2018-04-12 07:23
Duplicate of #10.

**Closed as completed** 2018-04-23 21:39 UTC
